### ISSUE TITLE
Abstract on class isn't rendered

### ISSUE THREAD

**Issue by Gijsjan** [croquiscom/crojsdoc#21]
When I declare a class to be abstract, it doesn't show that it's abstract in the docs. I see in [the code](https://github.com/croquiscom/crojsdoc/blob/1774e5c4ab20ab6440f7e8d26fcb18c24d25a4f3/themes/default/templates/class.jade#L22-23) that it checks for abstract on properties, but couldn't find where the template renders abstract. Am I missing something?

**Comment by sixmen** [comment]
The code is for properties of class. 'abstract' is not shown for class.
Please tell me a display style(e.x. *abstract* MyClass or MyClass [abstract]) that you want, then I'll add it.

**Comment by sixmen** [comment]
override tag is displayed like this http://croquiscom.github.io/cormo/classes/adapter.MongoDBAdapter.html

**Comment by Gijsjan** [comment]
Ah, I see I forgot to add a name to the @override tag. Thank you for the example.

I would suggest render the abstract label the same on a class as on a property, so `<span class="label label-abstract">abstract</span>` right after the class name.
